### ISSUE TITLE
Better explain the process, timeline and requirements of a dispute

### ISSUE THREAD

**Issue by marsrobertson** [kleros/escrow#27]
Related to #24

# Make it clear both parties have to pay
![image](https://user-images.githubusercontent.com/44369284/56421379-1d71e580-629a-11e9-8d29-4c73db7282db.png)

# Make it clear "burden proof" is on you

It has be the guy who raises a dispute to convince jurors.

The default position is "innocent until proven guilty", it is your job to convince jurors.

![image](https://user-images.githubusercontent.com/44369284/56421677-9160bd80-629b-11e9-9239-cfc83b0b90fb.png)

# EDIT

It is not clear what is the default position.

Seems like by default everyone is losing LOL...

![image](https://user-images.githubusercontent.com/44369284/56424050-8fe8c280-62a6-11e9-83a5-16e37a978bbd.png)

**Comment by satello** [comment]
It is unnecessary information that both parties need to pay. From the perspective of a single party if the other person doesn't pay they just win the dispute. There is a burden of proof for both parties in the dispute and it is implied.

**Comment by marsrobertson** [comment]
> It is unnecessary information that both parties need to pay. 

I was surprised that other party has to pay.

> From the perspective of a single party if the other person doesn't pay they just win the dispute.

Maybe.

I prefer transparency, clarity, full information.

As a poweruser who has loads of ETH and been through disputes I can bully a small guy who doesn't have 0.64 ETH.

_(whether we allow crowdfunding of arbitration fees is another issue)_

Bottom line: **make the whole process transparent**. If someone knows how to read the code, they can analyse the contract on Etherscan anyway.

> There is a burden of proof for both parties in the dispute and it is implied.

Tell me more.

My real life differences show different reality.

Bottom line: **make the whole process transparent**. How is it implied and what does it mean that both parties have burden of proof?

**Comment by satello** [comment]
It is a balance between full transparency and creating something that is user friendly. If we include a full explainer of what is happening behind the scenes in the smart contract in the UI it will just clutter it and make the whole process much more confusing to the average user vs making something that "just works". I think things such as explaining the arbitration fee process belongs in a longer form tutorial or article instead of the flow of the UI itself.

As for the burden of proof: The jurors do not know who initially raised the dispute so there isn't much of a concept of which side is "innocent until proven guilty". Naturally as a party in a dispute if you see one side saying something you disagree with you will try to explain your side of things. It is again an issue of keeping the UI simple. There could be a whole tutorial on things like "how to make my case effectively in a Kleros dispute" that belongs outside of the direct flow of the UI.

**Comment by marsrobertson** [comment]
Fair comment.

Simple UI.

Explanation somewhere else.

Currently I'm facing the following issues:

https://github.com/kleros/tokens-on-trial/issues/26 - _"Provide more information about the timeline of the dispute"_

https://github.com/kleros/escrow/issues/21 - _"More clarity when communicating the % of original invoice, dispute, refund"_

All this information is currently available reading directly from Etherscan. I'd rather see it as the first class citizen in the UI. Currently a lot of metadata is lost. As a user I'd like to know more about timeline, details, any additional information (that is public anyway).
