### ISSUE TITLE
Are we assuming tokens from TCR have 18 decimals? (noone asked me how many they have)

### ISSUE THREAD

**Issue by marsrobertson** [kleros/escrow#64]
Similar to #61 

Adding new tokens - being asked for decimals.

Using tokens from TCR - noone is asking for decimals.

Are we making any assumptions?

There are som legitimate tokens with a different number of decimals, just lik BNB and GNT are not ERC20 BTW :)

**Comment by satello** [comment]
In hindsight we wish we had added decimal places as a field in the T2CR. Since we do not have that, we are looking up the decimal places in the contract. If it is not in the contract it is assumed 18 decimal places and we have a warning message on the confirmation page. `decimals` is an optional field in the ERC20 standard so there are a few cases of tokens that are not 18 and cannot be looked up. If you want different decimals you will need to create a Custom Token that can have the same information as the verified token but different decimal places.

**Comment by marsrobertson** [comment]
> we are looking up the decimal places in the contract
> if it is not in the contract it is assumed 18 decimal places
> a few cases of tokens that are not 18 and cannot be looked up

Thank you for the explanation.

I understand better now.

----

Just a thought. Superset of TCR. All the existing data + decimals?

**Comment by marsrobertson** [comment]
We could have a "decimals curated registry" or a superset or a migration.

I'm worried we invested engineering resources into something unnecessarily overcomplicated.

I'm worried we solved the wrong problem. 

Handling edge cases and promoting users with warning messages.

Water under the bridge. New reality. New decade.

Full support.
